# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salestring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sumsale', models.FloatField()),
                ('day_code', models.IntegerField()),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]

